spkid:
  cls: spkanon_eval.featex.SpkIdConcat
  train: false
  trainer_cfg: null
  models:
    - path: speechbrain/spkrec-xvect-voxceleb
      train: false
      trainer_cfg: spkanon_eval/config/trainers/spkid.yaml
    - path: speechbrain/spkrec-ecapa-voxceleb
      train: false
      trainer_cfg: spkanon_eval/config/trainers/spkid.yaml
