spkid:
  cls: spkanon_eval.featex.spkid.spkid_concat.SpkIdConcat
  train: false
  trainer_cfg: config/trainers/spkid.yaml
  models:
    - path: speechbrain/spkrec-xvect-voxceleb
      train: false
      trainer_cfg: config/trainers/spkid.yaml
    - path: speechbrain/spkrec-ecapa-voxceleb
      train: false
      trainer_cfg: config/trainers/spkid.yaml
