spkid:
  cls: spkanon_eval.featex.spkid.spkid.SpkId # cls that extracts this feature
  path: speechbrain/spkrec-ecapa-voxceleb # path to ckpt or name of pretrained model
  train: false
  trainer_cfg: config/trainers/spkid.yaml
