spkid:
  cls: src.featex.spkid.spkid.SpkId # cls that extracts this feature
  toolkit: speechbrain
  path: speechbrain/spkrec-ecapa-voxceleb # path to ckpt or name of pretrained model
  train: false
  trainer_cfg: config/trainers/spkid.yaml
