spkid:
  cls: spkanon_eval.featex.SpkId # cls that extracts this feature
  path: speechbrain/spkrec-ecapa-voxceleb # path to ckpt or name of pretrained model
  emb_model_ckpt: ${eval.config.spkid_emb_model_ckpt} # path to ckpt of embedding model
  train: ${eval.config.spkid_train}
  batch_size: 32
  num_workers: ${data.config.num_workers}
  train_config: spkanon_eval/config/components/spkid/train_ecapa_debug.yaml
