spkid:
  cls: src.featex.spkid.spkid_concat.SpkIdConcat
  train: false
  trainer_cfg: config/trainers/spkid.yaml
  models:
    - toolkit: speechbrain
      path: speechbrain/spkrec-xvect-voxceleb
      train: false
      trainer_cfg: config/trainers/spkid.yaml
    - toolkit: speechbrain
      path: speechbrain/spkrec-ecapa-voxceleb
      train: false
      trainer_cfg: config/trainers/spkid.yaml
