spkid:
  cls: spkanon_eval.featex.spkid.spkid.SpkId # cls that extracts this feature
  path: speechbrain/spkrec-xvect-voxceleb # path to ckpt or name of pretrained model
  train: true
  batch_size: 24
  num_workers: ${data.config.num_workers}
  finetune_config: spkanon_eval/config/components/spkid/train_xvec.yaml
