spkid:
  cls: spkanon_eval.featex.spkid.spkid.SpkId # cls that extracts this feature
  path: speechbrain/spkrec-xvect-voxceleb # path to ckpt or name of pretrained model
  batch_size: 24
  num_workers: ${data.config.num_workers}
  finetune_config: spkanon_eval/config/components/spkid/train_xvec.yaml
  emb_model_ckpt: ${eval.config.spkid_emb_model_ckpt} # path to ckpt of embedding model
  train: ${eval.config.spkid_train}
