repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
        exclude: train_(ecapa|xvector)*
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: unittest-with-coverage
        name: unittest with coverage
        entry: bash -c 'cd .. && ./spane/build/run_tests.sh && cd ./spane'
        language: system
        pass_filenames: false
        stages: [push]
        working_directory: ..
