# This config contains the default values for training HiFi-GAN model on LJSpeech dataset.
# If you want to train model on other dataset, you can change config values according to your dataset.
# Most dataset-specific arguments are in the head of the config file, see below.

# Default values for dataset with sample_rate=22050
n_mel_channels: 960 # n_channels
n_window_size: 1024
n_window_stride: 256
n_fft: 1024
lowfreq: 0
highfreq: 8000
window: hann

generator:
  _target_: nemo.collections.tts.modules.hifigan_modules.Generator
  resblock: 1
  upsample_rates: [10, 8, 2, 2]
  upsample_kernel_sizes: [16, 16, 4, 4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  initial_input_size: ${synthesis.n_mel_channels}

preprocessor:
  _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
  nfilt: ${synthesis.n_mel_channels}
  lowfreq: ${synthesis.lowfreq}
  highfreq: ${synthesis.highfreq}
  n_fft: ${synthesis.n_fft}
  n_window_size: ${synthesis.n_window_size}
  n_window_stride: ${synthesis.n_window_stride}
  pad_to: 0
  pad_value: -11.52
  sample_rate: ${data.config.sample_rate}
  window: ${synthesis.window}
  normalize: null
  preemph: null
  dither: 0.0
  frame_splicing: 1
  log: true
  log_zero_guard_type: clamp
  log_zero_guard_value: 1e-05
  mag_power: 1.0
  use_grads: false
  exact_pad: true
