# the same target is always selected

target_selection:
  extra_args: # anonymizer args required by the algorithm, besides the config and vectors
    - log_dir
    - device
  cls: spkanon_eval.target_selection.asv_based.AsvSelector
  consistent_targets: true # whether the same target should always be used for the same source
  data: ${data} # should have config and datasets.train_targetselection
  asv_cfg: config/components/asv/ecapa.yaml
  pipeline:
    target_selection_cfg: config/components/target_selection/random.yaml
    resources: ${resources}
    featproc: ${featproc}
    synthesis: ${synthesis}
  train: true
