target_selection:
  cls: spkanon_eval.target_selection.RandomSelector
  consistent_targets: ${inference.consistent_targets} # whether the same target should always be used for the same source
  gender_conversion: ${inference.gender_conversion}
