# minimal datasets for debugging
data:
  config_cfg: spane/config/datasets/config.yaml
  datasets:
    eval:
      # - spane/data/debug/edacc-test.txt
      - spane/data/debug/ls-dev-clean-2.txt
      # - spane/data/debug/cv-test.txt
      # - spane/data/debug/ravdess.txt
    train_eval: # data to train the evaluation systems
      - spane/data/debug/ls-train-clean-5.txt
    targets:
      - spane/data/debug/ls-dev-clean-2.txt
    asv:
      trials: spane/data/debug/ls-dev-clean-2_trials.txt
      enrolls: spane/data/debug/ls-dev-clean-2_enrolls.txt
