data:
  config: # details of the data (TODO: should this differ for each dataset?)
    trainer: ${trainer}
    root_folder: /ds/audio
    sample_rate: ${sample_rate}
    trim_silence: false # apply voice activity detection (VAD)
    shuffle: false
    min_duration: 2
    max_duration: 25

  datasets:
    eval:
      - spkanon_eval/data/debug/edacc-test.txt
      - spkanon_eval/data/debug/ls-dev-clean-2.txt
      - spkanon_eval/data/debug/cv-test.txt
      - spkanon_eval/data/ravdess/ravdess.txt
    train_eval: # data to train the evaluation systems
      - spkanon_eval/data/debug/ls-dev-clean-2.txt
