data:
  config_cfg: spane/config/datasets/config.yaml
  datasets:
    eval:
      - spane/data/msp_podcast/msp-test1.txt
      - spane/data/ravdess/ravdess.txt
    targets:
      - spane/data/librispeech/ls-train-clean-100.txt
