data:
  config: # details of the data (TODO: should this differ for each dataset?)
    root_folder: /ds/audio
    sample_rate: ${sample_rate} # depends on the anonymization model
    batch_size: ${batch_size} # depends on the anonymization model
    min_duration: 2
    max_duration: 30

  datasets:
    eval:
      - spkanon_eval/data/common_voice/cv-test_3utts.txt
      - spkanon_eval/data/librispeech/ls-test-clean.txt
      - spkanon_eval/data/edacc/edacc-test.txt
      - spkanon_eval/data/ravdess/ravdess.txt
    train_eval:
      - spkanon_eval/data/librispeech/ls-train-clean-100.txt
      - spkanon_eval/data/edacc/edacc-dev.txt
