data:
  config_cfg: spkanon_eval/config/datasets/config.yaml
  datasets:
    eval:
      - spkanon_eval/data/common_voice/cv-test_3utts.txt
      - spkanon_eval/data/librispeech/ls-test-clean.txt
      - spkanon_eval/data/edacc/edacc-test.txt
      - spkanon_eval/data/ravdess/ravdess.txt
    train_eval:
      - spkanon_eval/data/librispeech/ls-train-clean-100.txt
      - spkanon_eval/data/edacc/edacc-dev.txt
    targets:
      - spkanon_eval/data/librispeech/ls-train-clean-5.txt
