data:
  config_cfg: spane/config/datasets/config.yaml
  datasets:
    eval:
      - spane/data/librispeech/ls-test-clean_max30s.txt
    train_eval:
      - spane/data/librispeech/ls-train-clean-360.txt
    targets:
      - spkanon/spane/data/libritts/tts-train-other-500_subset.txt
    asv:
      trials:
        - spane/data/librispeech/privacy_eval/ls-test-clean_trials.txt
      enrolls:
        - spane/data/librispeech/privacy_eval/ls-test-clean_enrolls.txt
