data:
  config:
    sample_rate: 16000
    root_folder: /ds/audio
    max_ratio: ${max_ratio}

  datasets:
    eval:
      - spkanon_eval/data/librispeech/ls-test-clean.txt
    train_eval:
      - spkanon_eval/data/librispeech/ls-train-clean-360.txt
    targets:
      - spkanon_eval/data/librispeech/ls-train-clean-100.txt
    enrolls:
      - spkanon_eval/data/librispeech/ls-test-clean-enrolls.txt
