data:
  config_cfg: spkanon_eval/config/datasets/config.yaml
  datasets:
    eval:
      - spkanon_eval/data/librispeech/ls-test-clean.txt
    train_eval:
      - spkanon_eval/data/librispeech/ls-train-clean-360.txt
    targets:
      - /netscratch/franzreb/spkanon/configs/knnvc_private_mine/target_feats/datafiles/top_gender.txt
    enrolls:
      - spkanon_eval/data/librispeech/ls-test-clean-enrolls.txt
