data:
  config_cfg: spkanon_eval/config/datasets/config.yaml
  datasets:
    eval:
      - spkanon_eval/data/librispeech/ls-test-clean.txt
    train_eval:
      - spkanon_eval/data/mini_librispeech/ls-dev-clean-2.txt
    targets:
      - spkanon_eval/data/librispeech/ls-test-other.txt
    enrolls:
      - spkanon_eval/data/librispeech/ls-test-clean-enrolls.txt
