data:
  config: # details of the data (TODO: should this differ for each dataset?)
    root_folder: /Users/cafr02/datasets
    sample_rate: ${sample_rate} # depends on the anonymization model
    batch_size: ${batch_size} # depends on the anonymization model

  datasets:
    eval:
      - spkanon_eval/data/debug/ls-dev-clean-2.txt
    train_eval:
      - spkanon_eval/data/debug/ls-train-clean-5.txt
    targets:
      - spkanon_eval/data/debug/ls-dev-clean-2.txt
