data:
  config: # details of the data (TODO: should this differ for each dataset?)
    root_folder: /ds/audio
    sample_rate: ${sample_rate} # depends on the anonymization model
    batch_size: ${batch_size} # depends on the anonymization model

  datasets:
    eval:
      - spkanon_eval/data/librispeech/test-clean.txt
    train_pipeline: # data to train the synthesizer (if necessary).
      - spkanon_eval/data/librispeech/train-clean-100.txt
      - spkanon_eval/data/librispeech/train-other-500.txt
    train_eval:
      - spkanon_eval/data/librispeech/train-clean-360.txt
