# for running the privacy evaluation only
# only the utterances required by the privacy evaluation are anonymized
data:
  config_cfg: spane/config/datasets/config.yaml
  datasets:
    eval:
      - spane/data/librispeech/privacy_eval/ls-test-clean_privacy-eval.txt
    train_eval:
      - spane/data/librispeech/ls-train-clean-360.txt
    targets:
      - spane/data/librispeech/ls-train-clean-100.txt
    asv:
      enrolls:
        - spane/data/librispeech/privacy_eval/ls-test-clean_trials.txt
