datasets_cfg: spane/config/datasets/librispeech.yaml
seed: 0
log_dir: logs/knnvc_private
device: cpu # overwritten on runtime

inference:
  run: true # anonymize utterances
  input: # input of the `infer` method of the anonymizer
    spectrogram: spectrogram # key under which the spectrogram can be found
    target: target

target_selection_cfg: spane/config/components/target_selection/random.yaml
pipeline_cfg: spane/spkanon_models/knnvc_private/config.yaml # must clone spkanon_models repo first (see README)
converter_params:
  target_feats: null
  duration_prediction_weight: 0.7
  n_phone_clusters: 8
  phone_predictor_ckpt: checkpoints/phone_decoder.pt
  duration_predictor_ckpt: checkpoints/duration_decoder.pt
  phone_lexicon: spane/spkanon_models/knnvc_private/phone_lexicon.txt
  n_anonymizations: 1

eval: # calls func `eval_dir` of each component
  config:
    seed: 300
    baseline: false # non-anonymized speech is evaluated; inference and train must be false, eval must be present
    exp_folder: null # if not null, this folder is evaluated instead of current exp_folder

  components:
    asv_cfg: spane/config/components/asv/config.yaml
    small_asr_cfg: spane/config/components/asr/whisper_small.yaml
    large_asr_cfg: spane/config/components/asr/whisper_large.yaml
    naturalness_cfg: spane/config/components/naturalness/nisqa.yaml
    performance_cfg: spane/config/components/performance/performance_20s.yaml
    # ser_cfg: spane/config/components/ser/audeering_w2v.yaml
