datasets_cfg: spkanon_eval/config/datasets/librispeech.yaml
seed: 0
log_dir: logs/train_spkembs
device: cpu # overwritten on runtime

inference:
  run: false # store anonymized utterances; can be true, false or a path to an exp folder
  input: # input of the `infer` method of the anonymizer
    spectrogram: spectrogram # key under which the spectrogram can be found
    target: target

target_selection_cfg: spkanon_eval/config/components/target_selection/random.yaml
pipeline_cfg: spkanon_eval/spkanon_models/stargan/config.yaml # must clone spkanon_models repo first (see README)

eval: # calls func `eval_dir` of each component, passing exp_folder and config
  config:
    seed: 300
    baseline: false # non-anonymized speech is evaluated; inference and train must be false, eval must be present
    exp_folder: logs/train_spkembs/1716903870 # if not null, this folder is evaluated instead of current exp_folder
    sample_rate: ${synthesis.sample_rate} # SR of the anonymized data
    asv_reduce_dims: null
    asv_spkid_cfg: spkanon_eval/config/components/spkid/ecapa.yaml
    spkid_emb_model_ckpt: null
    spkid_train: true

  components:
    # asv_ignorant_cfg: trained_asv_configs/ignorant.yaml
    asv_plda_lazy_informed_cfg: spkanon_eval/config/components/asv/plda/lazy-informed.yaml
    # small_asr_cfg: spkanon_eval/config/components/asr/whisper_small.yaml
    # large_asr_cfg: spkanon_eval/config/components/asr/whisper_large.yaml
    # ser_cfg: spkanon_eval/config/components/ser/audeering_w2v.yaml
    # naturalness_cfg: spkanon_eval/config/components/naturalness/nisqa.yaml
