# this config must be a child of the `eval.components` config
asv_ignorant:
  cls: spkanon_eval.evaluation.ASV
  scenario: ignorant # attack scenario; can be ignorant or lazy-informed
  train: true
  reduced_dims: ${eval.config.asv_reduce_dims} # (optional) no. of dimensions to reduce the spkid vectors to (VPC uses 200)
  lda_ckpt: null
  plda_ckpt: null
  spkid: ${eval.config.spkid}
