# this config must be a child of the `eval.components` config
asv_ignorant:
  cls: spkanon_eval.evaluation.asv.spkid_plda.ASV
  scenario: ignorant # attack scenario; can be ignorant or lazy-informed
  train: true
  reduced_dims: ${eval.config.asv_reduce_dims} # (optional) no. of dimensions to reduce the spkid vectors to (VPC uses 200)
  lda_ckpt: null
  plda_ckpt: null
  filter: # (optional) filter out samples that don't meet these criteria
    min_dur: 4 # min. duration (in s) for each utterance
    min_samples: 2 # min. no. of samples per speaker
  spkid: ${eval.config.spkid}
