# TODO: only run this if Python files or this workflow changed.
name: Build and test with coverage

on:
  push:
    branches:
      - master
      - better_batches
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          cd ..
          bash ./spkanon_eval/build/framework.sh

      - name: Create .coveragerc
        run: |
          cat <<EOF > ../.coveragerc
          [report]
          include = spkanon_eval/*
          EOF

      - name: Coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          working-directory: ..
