name: Build

on:
  push:
    branches:
      - master
      - better_batches
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          cd ..
          bash ./spkanon_eval/build/framework.sh