spkid:
  cls: spkanon_eval.featex.SpkId # cls that extracts this feature
  path: speechbrain/spkrec-ecapa-voxceleb # path to ckpt or name of pretrained model
  ckpt: ${eval.config.asv.spkid_ckpt} # path to ckpt of embedding model
  train: ${eval.config.asv.train_spkid}
  batch_size: 32
  num_workers: ${data.config.num_workers}
  train_config: spkanon_eval/config/components/asv/spkid/train_ecapa.yaml
